[2024-05-27T16:38:22.533+0000] {processor.py:161} INFO - Started process (PID=638) to work on /opt/airflow/dags/new_dag.py
[2024-05-27T16:38:22.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/new_dag.py for tasks to queue
[2024-05-27T16:38:22.536+0000] {logging_mixin.py:188} INFO - [2024-05-27T16:38:22.536+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/new_dag.py
[2024-05-27T16:38:23.591+0000] {logging_mixin.py:188} INFO - [2024-05-27T16:38:23.586+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/new_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/new_dag.py", line 4, in <module>
    from text_classification_pkg.text_classification_module import (
ImportError: cannot import name 'create_postgres_database' from 'text_classification_pkg.text_classification_module' (/opt/airflow/dags/text_classification_pkg/text_classification_module.py)
[2024-05-27T16:38:23.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/new_dag.py
[2024-05-27T16:38:23.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/new_dag.py took 1.088 seconds
